# Generated by Django 2.2.12 on 2020-09-17 18:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(help_text='Name of the merchant', max_length=32, unique=True)),
                ('email', models.EmailField(help_text='Email of the merchant', max_length=64)),
                ('discount_rate', models.DecimalField(decimal_places=2, help_text='Discount provided by the merchant', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Purchase amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('merchant_discount', models.DecimalField(decimal_places=2, help_text='Merchant Discount. This amount is our application fee', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimplUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Name of the user', max_length=32, unique=True)),
                ('email', models.EmailField(help_text='Email of the user', max_length=64)),
                ('credit_limit', models.IntegerField(help_text='Max Usable Credit Amount', validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('available_credit_limit', models.IntegerField(help_text='Available Credit Amount', validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='simpluser',
            constraint=models.CheckConstraint(check=models.Q(credit_limit__gte=0), name='simpluser_credit_limit_min_0_constraint'),
        ),
        migrations.AddConstraint(
            model_name='simpluser',
            constraint=models.CheckConstraint(check=models.Q(('available_credit_limit__gte', 0), ('available_credit_limit__lte', django.db.models.expressions.F('credit_limit'))), name='simpluser_available_credit_limit_constraint'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='merchant',
            field=models.ForeignKey(help_text='Merchant user made the purchase from', on_delete=django.db.models.deletion.PROTECT, to='pay_later_app.Merchant'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='simpluser',
            field=models.ForeignKey(help_text='User who made the purchase', on_delete=django.db.models.deletion.PROTECT, to='pay_later_app.SimplUser'),
        ),
        migrations.AddField(
            model_name='payment',
            name='simpluser',
            field=models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.PROTECT, to='pay_later_app.SimplUser'),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.CheckConstraint(check=models.Q(('discount_rate__gte', 0), ('discount_rate__lte', 100)), name='merchant_discount_rate_constraint'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(check=models.Q(amount__gte=0), name='purchase_amount_min_0_constraint'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(amount__gte=0), name='payment_amount_min_0_constraint'),
        ),
    ]
